development:
  adapter: postgresql
  host: localhost
  username: postgres
  password: cp400102
  database: point_dev
test:
  adapter: postgresql
  host: localhost
  username: postgres
  password: cp400102
  database: point_test
production:
  adapter: postgresql
  host: localhost
  username: postgres
  password: cp400102
  database: point_prod